#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: dea06d81-33d4-4e95-a834-a1fca7ee7b10
# Source File: C:\Users\Lenovo\Documents\SAPIEN\PowerShell Studio\Projects\Scryptero\Scryptero.psproj
#------------------------------------------------------------------------
<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2018 v5.5.150
     Generated on:       10.05.2018 17:19
     Generated by:       Lenovo
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2018
#>



#region Source: Startup.pss
#----------------------------------------------
#region Import Assemblies
#----------------------------------------------
[void][Reflection.Assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
[void][Reflection.Assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
#endregion Import Assemblies

#Define a Param block to use custom parameters in the project
#Param ($CustomParameter)

function Main {
<#
    .SYNOPSIS
        The Main function starts the project application.
    
    .PARAMETER Commandline
        $Commandline contains the complete argument string passed to the script packager executable.
    
    .NOTES
        Use this function to initialize your script and to call GUI forms.
		
    .NOTES
        To get the console output in the Packager (Forms Engine) use: 
		$ConsoleOutput (Type: System.Collections.ArrayList)
#>
	Param ([String]$Commandline)
		
	#--------------------------------------------------------------------------
	#TODO: Add initialization script here (Load modules and check requirements)
	
	
	#--------------------------------------------------------------------------
	
	if((Show-MainForm_psf) -eq 'OK')
	{
		
	}
	
	$script:ExitCode = 0 #Set the exit code for the Packager
}







#endregion Source: Startup.pss

#region Source: MainForm.psf
function Show-MainForm_psf
{
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$Scryptero = New-Object 'System.Windows.Forms.Form'
	$groupbox1 = New-Object 'System.Windows.Forms.GroupBox'
	$buttonSecmasterPass = New-Object 'System.Windows.Forms.Button'
	$buttonCheckExt3Att = New-Object 'System.Windows.Forms.Button'
	$groupboxGlobalData = New-Object 'System.Windows.Forms.GroupBox'
	$labelMacAdress = New-Object 'System.Windows.Forms.Label'
	$labelUserID = New-Object 'System.Windows.Forms.Label'
	$labelComputerName = New-Object 'System.Windows.Forms.Label'
	$buttonUserID = New-Object 'System.Windows.Forms.Button'
	$textboxMacAddress = New-Object 'System.Windows.Forms.TextBox'
	$textbox2 = New-Object 'System.Windows.Forms.TextBox'
	$textboxComputerNameMainForm = New-Object 'System.Windows.Forms.TextBox'
	$buttonComputerName = New-Object 'System.Windows.Forms.Button'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$Scryptero_Load={
	#TODO: Initialize Form Controls here
	
	}
	
	$buttonCheckExt3Att_Click={
		#TODO: Place custom script here
		
		if ((Show-ChildForm_psf) -eq 'OK')
		{
			Out-Default $textboxMacAddress
		}
		
	}
	
	$buttonSecmasterPass_Click={
		#TODO: Place custom script here
		if ((Show-SecmasterPasswordForm_psf) -eq 'OK')
		{
			Out-Default $textboxComputerNameMainForm
		}
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$Scryptero.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
		$script:MainForm_textboxMacAddress = $textboxMacAddress.Text
		$script:MainForm_textbox2 = $textbox2.Text
		$script:MainForm_textboxComputerNameMainForm = $textboxComputerNameMainForm.Text
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonSecmasterPass.remove_Click($buttonSecmasterPass_Click)
			$buttonCheckExt3Att.remove_Click($buttonCheckExt3Att_Click)
			$Scryptero.remove_Load($Scryptero_Load)
			$Scryptero.remove_Load($Form_StateCorrection_Load)
			$Scryptero.remove_Closing($Form_StoreValues_Closing)
			$Scryptero.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$Scryptero.SuspendLayout()
	$groupbox1.SuspendLayout()
	$groupboxGlobalData.SuspendLayout()
	#
	# Scryptero
	#
	$Scryptero.Controls.Add($groupbox1)
	$Scryptero.Controls.Add($groupboxGlobalData)
	$Scryptero.AutoScaleDimensions = '6, 13'
	$Scryptero.AutoScaleMode = 'Font'
	$Scryptero.ClientSize = '432, 430'
	$Scryptero.Name = 'Scryptero'
	$Scryptero.StartPosition = 'CenterScreen'
	$Scryptero.Text = 'Scryptero'
	$Scryptero.add_Load($Scryptero_Load)
	#
	# groupbox1
	#
	$groupbox1.Controls.Add($buttonSecmasterPass)
	$groupbox1.Controls.Add($buttonCheckExt3Att)
	$groupbox1.Location = '13, 134'
	$groupbox1.Name = 'groupbox1'
	$groupbox1.Size = '407, 118'
	$groupbox1.TabIndex = 2
	$groupbox1.TabStop = $False
	$groupbox1.Text = 'Script'
	$groupbox1.UseCompatibleTextRendering = $True
	#
	# buttonSecmasterPass
	#
	$buttonSecmasterPass.Location = '148, 19'
	$buttonSecmasterPass.Name = 'buttonSecmasterPass'
	$buttonSecmasterPass.Size = '73, 23'
	$buttonSecmasterPass.TabIndex = 1
	$buttonSecmasterPass.Text = 'Secmaster Password'
	$buttonSecmasterPass.UseCompatibleTextRendering = $True
	$buttonSecmasterPass.UseVisualStyleBackColor = $True
	$buttonSecmasterPass.add_Click($buttonSecmasterPass_Click)
	#
	# buttonCheckExt3Att
	#
	$buttonCheckExt3Att.Anchor = 'None'
	$buttonCheckExt3Att.Location = '7, 19'
	$buttonCheckExt3Att.Name = 'buttonCheckExt3Att'
	$buttonCheckExt3Att.Size = '134, 23'
	$buttonCheckExt3Att.TabIndex = 0
	$buttonCheckExt3Att.Text = 'Check Extension Att'
	$buttonCheckExt3Att.UseCompatibleTextRendering = $True
	$buttonCheckExt3Att.UseVisualStyleBackColor = $True
	$buttonCheckExt3Att.add_Click($buttonCheckExt3Att_Click)
	#
	# groupboxGlobalData
	#
	$groupboxGlobalData.Controls.Add($labelMacAdress)
	$groupboxGlobalData.Controls.Add($labelUserID)
	$groupboxGlobalData.Controls.Add($labelComputerName)
	$groupboxGlobalData.Controls.Add($buttonUserID)
	$groupboxGlobalData.Controls.Add($textboxMacAddress)
	$groupboxGlobalData.Controls.Add($textbox2)
	$groupboxGlobalData.Controls.Add($textboxComputerNameMainForm)
	$groupboxGlobalData.Controls.Add($buttonComputerName)
	$groupboxGlobalData.Location = '13, 13'
	$groupboxGlobalData.Name = 'groupboxGlobalData'
	$groupboxGlobalData.Size = '407, 115'
	$groupboxGlobalData.TabIndex = 1
	$groupboxGlobalData.TabStop = $False
	$groupboxGlobalData.Text = 'Global data'
	$groupboxGlobalData.UseCompatibleTextRendering = $True
	#
	# labelMacAdress
	#
	$labelMacAdress.AutoSize = $True
	$labelMacAdress.Location = '7, 71'
	$labelMacAdress.Name = 'labelMacAdress'
	$labelMacAdress.Size = '75, 17'
	$labelMacAdress.TabIndex = 7
	$labelMacAdress.Text = 'Mac address :'
	$labelMacAdress.UseCompatibleTextRendering = $True
	#
	# labelUserID
	#
	$labelUserID.AutoSize = $True
	$labelUserID.Location = '7, 45'
	$labelUserID.Name = 'labelUserID'
	$labelUserID.Size = '49, 17'
	$labelUserID.TabIndex = 6
	$labelUserID.Text = 'User ID :'
	$labelUserID.UseCompatibleTextRendering = $True
	#
	# labelComputerName
	#
	$labelComputerName.AutoSize = $True
	$labelComputerName.Location = '7, 19'
	$labelComputerName.Name = 'labelComputerName'
	$labelComputerName.Size = '91, 17'
	$labelComputerName.TabIndex = 5
	$labelComputerName.Text = 'Computer name :'
	$labelComputerName.UseCompatibleTextRendering = $True
	#
	# buttonUserID
	#
	$buttonUserID.Location = '303, 45'
	$buttonUserID.Name = 'buttonUserID'
	$buttonUserID.Size = '98, 23'
	$buttonUserID.TabIndex = 4
	$buttonUserID.Text = 'Search'
	$buttonUserID.UseCompatibleTextRendering = $True
	$buttonUserID.UseVisualStyleBackColor = $True
	#
	# textboxMacAddress
	#
	$textboxMacAddress.Location = '114, 71'
	$textboxMacAddress.Name = 'textboxMacAddress'
	$textboxMacAddress.Size = '165, 20'
	$textboxMacAddress.TabIndex = 3
	#
	# textbox2
	#
	$textbox2.Location = '114, 45'
	$textbox2.Name = 'textbox2'
	$textbox2.Size = '165, 20'
	$textbox2.TabIndex = 2
	#
	# textboxComputerNameMainForm
	#
	$textboxComputerNameMainForm.Location = '114, 19'
	$textboxComputerNameMainForm.Name = 'textboxComputerNameMainForm'
	$textboxComputerNameMainForm.Size = '165, 20'
	$textboxComputerNameMainForm.TabIndex = 1
	#
	# buttonComputerName
	#
	$buttonComputerName.Location = '303, 18'
	$buttonComputerName.Name = 'buttonComputerName'
	$buttonComputerName.Size = '98, 23'
	$buttonComputerName.TabIndex = 0
	$buttonComputerName.Text = 'Search'
	$buttonComputerName.UseCompatibleTextRendering = $True
	$buttonComputerName.UseVisualStyleBackColor = $True
	$groupboxGlobalData.ResumeLayout()
	$groupbox1.ResumeLayout()
	$Scryptero.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $Scryptero.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$Scryptero.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$Scryptero.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$Scryptero.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $Scryptero.ShowDialog()

}
#endregion Source: MainForm.psf

#region Source: Globals.ps1
	#--------------------------------------------
	# Declare Global Variables and Functions here
	#--------------------------------------------
	
	#Sample function that provides the location of the script
	function Get-ScriptDirectory
	{
	<#
		.SYNOPSIS
			Get-ScriptDirectory returns the proper location of the script.
	
		.OUTPUTS
			System.String
		
		.NOTES
			Returns the correct path within a packaged executable.
	#>
		[OutputType([string])]
		param ()
		if ($null -ne $hostinvocation)
		{
			Split-Path $hostinvocation.MyCommand.path
		}
		else
		{
			Split-Path $script:MyInvocation.MyCommand.Path
		}
	}
	
	#Sample variable that provides the location of the script
	[string]$ScriptDirectory = Get-ScriptDirectory
	
	
	
#endregion Source: Globals.ps1

#region Source: ChildForm.psf
function Show-ChildForm_psf
{
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$ChildFormExt3Att = New-Object 'System.Windows.Forms.Form'
	$textboxExt3Att = New-Object 'System.Windows.Forms.TextBox'
	$statusbarExt3Att = New-Object 'System.Windows.Forms.StatusBar'
	$labelMACOrComputerName = New-Object 'System.Windows.Forms.Label'
	$textboxMacOrComputerName = New-Object 'System.Windows.Forms.TextBox'
	$buttonExt3AttSearch = New-Object 'System.Windows.Forms.Button'
	$buttonDeleteExt3Att = New-Object 'System.Windows.Forms.Button'
	$buttonExit = New-Object 'System.Windows.Forms.Button'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	
	$ChildFormExt3Att_Load={
		#TODO: Initialize Form Controls here
		$textboxMacOrComputerName.Text = $textboxMacAddress.Text
	}
	
	
	$textboxMacOrComputerName_TextChanged={
		#TODO: Place custom script here
		
	}
	
	$labelMACOrComputerName_Click={
		#TODO: Place custom script here
		
	}
	
	$buttonExt3AttSearch_Click={
		#TODO: Place custom script here
		$mac = $textboxMacOrComputerName.Text
		$statusbarExt3Att.Text = "Searching..."
		
		try
		{
			foreach ($computer in Get-ADComputer -Filter * -SearchBase 'OU=WIN10,OU=Workstations,OU=BSK,DC=pl,DC=ing-ad' -Properties extensionAttribute3)
			{
				if ($computer.extensionAttribute3 -eq $mac)
				{
					$ComputerNameSearch = $computer.name
				}
			}
		}
		catch
		{
			$textboxExt3Att.Text = "Not found, check status bar informations."
			$statusbarExt3Att.Text = "Error : $($_.Exception.Message)"
		}
		
		if ($ComputerNameSearch -eq $null)
		{
			$textboxExt3Att.Text = "Not Found"
		}
		else
		{
			$textboxExt3Att.Text = "$($ComputerNameSearch)"
		}
		$statusbarExt3Att.Text = "Done."
	}
	
	$statusbarExt3Att_PanelClick=[System.Windows.Forms.StatusBarPanelClickEventHandler]{
	#Event Argument: $_ = [System.Windows.Forms.StatusBarPanelClickEventArgs]
		#TODO: Place custom script here
		
	}
	
	#region Control Helper Functions
	function Update-DataGridView
	{
		<#
		.SYNOPSIS
			This functions helps you load items into a DataGridView.
	
		.DESCRIPTION
			Use this function to dynamically load items into the DataGridView control.
	
		.PARAMETER  DataGridView
			The DataGridView control you want to add items to.
	
		.PARAMETER  Item
			The object or objects you wish to load into the DataGridView's items collection.
		
		.PARAMETER  DataMember
			Sets the name of the list or table in the data source for which the DataGridView is displaying data.
	
		.PARAMETER AutoSizeColumns
		    Resizes DataGridView control's columns after loading the items.
		#>
		Param (
			[ValidateNotNull()]
			[Parameter(Mandatory=$true)]
			[System.Windows.Forms.DataGridView]$DataGridView,
			[ValidateNotNull()]
			[Parameter(Mandatory=$true)]
			$Item,
		    [Parameter(Mandatory=$false)]
			[string]$DataMember,
			[System.Windows.Forms.DataGridViewAutoSizeColumnMode]$AutoSizeColumns = 'None'
		)
		$DataGridView.SuspendLayout()
		$DataGridView.DataMember = $DataMember
		
		if ($Item -is [System.Data.DataSet] -and $Item.Tables.Count -gt 0)
		{
			$DataGridView.DataSource = $Item.Tables[0]
		}
		elseif ($Item -is [System.ComponentModel.IListSource]`
		-or $Item -is [System.ComponentModel.IBindingList] -or $Item -is [System.ComponentModel.IBindingListView] )
		{
			$DataGridView.DataSource = $Item
		}
		else
		{
			$array = New-Object System.Collections.ArrayList
			
			if ($Item -is [System.Collections.IList])
			{
				$array.AddRange($Item)
			}
			else
			{
				$array.Add($Item)
			}
			$DataGridView.DataSource = $array
		}
		
		if ($AutoSizeColumns -ne 'None')
		{
			$DataGridView.AutoResizeColumns($AutoSizeColumns)
		}
		
		$DataGridView.ResumeLayout()
	}
	
	function ConvertTo-DataTable
	{
		<#
			.SYNOPSIS
				Converts objects into a DataTable.
		
			.DESCRIPTION
				Converts objects into a DataTable, which are used for DataBinding.
		
			.PARAMETER  InputObject
				The input to convert into a DataTable.
		
			.PARAMETER  Table
				The DataTable you wish to load the input into.
		
			.PARAMETER RetainColumns
				This switch tells the function to keep the DataTable's existing columns.
			
			.PARAMETER FilterWMIProperties
				This switch removes WMI properties that start with an underline.
		
			.EXAMPLE
				$DataTable = ConvertTo-DataTable -InputObject (Get-Process)
		#>
		[OutputType([System.Data.DataTable])]
		param(
		[ValidateNotNull()]
		$InputObject, 
		[ValidateNotNull()]
		[System.Data.DataTable]$Table,
		[switch]$RetainColumns,
		[switch]$FilterWMIProperties)
		
		if($null -eq $Table)
		{
			$Table = New-Object System.Data.DataTable
		}
		
		if ($InputObject -is [System.Data.DataTable])
		{
			$Table = $InputObject
		}
		elseif ($InputObject -is [System.Data.DataSet] -and $InputObject.Tables.Count -gt 0)
		{
			$Table = $InputObject.Tables[0]
		}
		else
		{
			if (-not $RetainColumns -or $Table.Columns.Count -eq 0)
			{
				#Clear out the Table Contents
				$Table.Clear()
				
				if ($null -eq $InputObject) { return } #Empty Data
				
				$object = $null
				#find the first non null value
				foreach ($item in $InputObject)
				{
					if ($null -ne $item)
					{
						$object = $item
						break
					}
				}
				
				if ($null -eq $object) { return } #All null then empty
				
				#Get all the properties in order to create the columns
				foreach ($prop in $object.PSObject.Get_Properties())
				{
					if (-not $FilterWMIProperties -or -not $prop.Name.StartsWith('__')) #filter out WMI properties
					{
						#Get the type from the Definition string
						$type = $null
						
						if ($null -ne $prop.Value)
						{
							try { $type = $prop.Value.GetType() }
							catch { Out-Null }
						}
						
						if ($null -ne $type) # -and [System.Type]::GetTypeCode($type) -ne 'Object')
						{
							[void]$table.Columns.Add($prop.Name, $type)
						}
						else #Type info not found
						{
							[void]$table.Columns.Add($prop.Name)
						}
					}
				}
				
				if ($object -is [System.Data.DataRow])
				{
					foreach ($item in $InputObject)
					{
						$Table.Rows.Add($item)
					}
					return @( ,$Table)
				}
			}
			else
			{
				$Table.Rows.Clear()
			}
			
			foreach ($item in $InputObject)
			{
				$row = $table.NewRow()
				
				if ($item)
				{
					foreach ($prop in $item.PSObject.Get_Properties())
					{
						if ($table.Columns.Contains($prop.Name))
						{
							$row.Item($prop.Name) = $prop.Value
						}
					}
				}
				[void]$table.Rows.Add($row)
			}
		}
		
		return @(,$Table)	
	}
	#endregion
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$ChildFormExt3Att.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
		$script:ChildForm_textboxExt3Att = $textboxExt3Att.Text
		$script:ChildForm_textboxMacOrComputerName = $textboxMacOrComputerName.Text
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$statusbarExt3Att.remove_PanelClick($statusbarExt3Att_PanelClick)
			$labelMACOrComputerName.remove_Click($labelMACOrComputerName_Click)
			$textboxMacOrComputerName.remove_TextChanged($textboxMacOrComputerName_TextChanged)
			$buttonExt3AttSearch.remove_Click($buttonExt3AttSearch_Click)
			$ChildFormExt3Att.remove_Load($ChildFormExt3Att_Load)
			$ChildFormExt3Att.remove_Load($Form_StateCorrection_Load)
			$ChildFormExt3Att.remove_Closing($Form_StoreValues_Closing)
			$ChildFormExt3Att.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$ChildFormExt3Att.SuspendLayout()
	#
	# ChildFormExt3Att
	#
	$ChildFormExt3Att.Controls.Add($textboxExt3Att)
	$ChildFormExt3Att.Controls.Add($statusbarExt3Att)
	$ChildFormExt3Att.Controls.Add($labelMACOrComputerName)
	$ChildFormExt3Att.Controls.Add($textboxMacOrComputerName)
	$ChildFormExt3Att.Controls.Add($buttonExt3AttSearch)
	$ChildFormExt3Att.Controls.Add($buttonDeleteExt3Att)
	$ChildFormExt3Att.Controls.Add($buttonExit)
	$ChildFormExt3Att.AutoScaleDimensions = '6, 13'
	$ChildFormExt3Att.AutoScaleMode = 'Font'
	$ChildFormExt3Att.ClientSize = '308, 167'
	$ChildFormExt3Att.Name = 'ChildFormExt3Att'
	$ChildFormExt3Att.StartPosition = 'CenterParent'
	$ChildFormExt3Att.Text = 'Checking Extension Attribute'
	$ChildFormExt3Att.add_Load($ChildFormExt3Att_Load)
	#
	# textboxExt3Att
	#
	$textboxExt3Att.Enabled = $False
	$textboxExt3Att.Location = '13, 78'
	$textboxExt3Att.Name = 'textboxExt3Att'
	$textboxExt3Att.Size = '283, 20'
	$textboxExt3Att.TabIndex = 7
	$textboxExt3Att.TextAlign = 'Right'
	#
	# statusbarExt3Att
	#
	$statusbarExt3Att.Location = '0, 145'
	$statusbarExt3Att.Name = 'statusbarExt3Att'
	$statusbarExt3Att.Size = '308, 22'
	$statusbarExt3Att.TabIndex = 6
	$statusbarExt3Att.Text = 'Ready to use ...'
	$statusbarExt3Att.add_PanelClick($statusbarExt3Att_PanelClick)
	#
	# labelMACOrComputerName
	#
	$labelMACOrComputerName.AutoSize = $True
	$labelMACOrComputerName.Location = '13, 18'
	$labelMACOrComputerName.Name = 'labelMACOrComputerName'
	$labelMACOrComputerName.Size = '130, 17'
	$labelMACOrComputerName.TabIndex = 4
	$labelMACOrComputerName.Text = 'MAC or computer name :'
	$labelMACOrComputerName.UseCompatibleTextRendering = $True
	$labelMACOrComputerName.add_Click($labelMACOrComputerName_Click)
	#
	# textboxMacOrComputerName
	#
	$textboxMacOrComputerName.Location = '149, 16'
	$textboxMacOrComputerName.Name = 'textboxMacOrComputerName'
	$textboxMacOrComputerName.Size = '147, 20'
	$textboxMacOrComputerName.TabIndex = 3
	$textboxMacOrComputerName.add_TextChanged($textboxMacOrComputerName_TextChanged)
	#
	# buttonExt3AttSearch
	#
	$buttonExt3AttSearch.Location = '221, 42'
	$buttonExt3AttSearch.Name = 'buttonExt3AttSearch'
	$buttonExt3AttSearch.Size = '75, 23'
	$buttonExt3AttSearch.TabIndex = 2
	$buttonExt3AttSearch.Text = 'Search'
	$buttonExt3AttSearch.UseCompatibleTextRendering = $True
	$buttonExt3AttSearch.UseVisualStyleBackColor = $True
	$buttonExt3AttSearch.add_Click($buttonExt3AttSearch_Click)
	#
	# buttonDeleteExt3Att
	#
	$buttonDeleteExt3Att.Anchor = 'Bottom, Right'
	$buttonDeleteExt3Att.DialogResult = 'OK'
	$buttonDeleteExt3Att.Location = '12, 116'
	$buttonDeleteExt3Att.Name = 'buttonDeleteExt3Att'
	$buttonDeleteExt3Att.Size = '105, 23'
	$buttonDeleteExt3Att.TabIndex = 1
	$buttonDeleteExt3Att.Text = 'Delete Attribute'
	$buttonDeleteExt3Att.UseCompatibleTextRendering = $True
	$buttonDeleteExt3Att.UseVisualStyleBackColor = $True
	#
	# buttonExit
	#
	$buttonExit.Anchor = 'Bottom, Right'
	$buttonExit.CausesValidation = $False
	$buttonExit.DialogResult = 'Cancel'
	$buttonExit.Location = '221, 116'
	$buttonExit.Name = 'buttonExit'
	$buttonExit.Size = '75, 23'
	$buttonExit.TabIndex = 0
	$buttonExit.Text = 'Exit'
	$buttonExit.UseCompatibleTextRendering = $True
	$buttonExit.UseVisualStyleBackColor = $True
	$ChildFormExt3Att.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $ChildFormExt3Att.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$ChildFormExt3Att.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$ChildFormExt3Att.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$ChildFormExt3Att.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $ChildFormExt3Att.ShowDialog()

}
#endregion Source: ChildForm.psf

#region Source: SecmasterPasswordForm.psf
function Show-SecmasterPasswordForm_psf
{
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formCheckingSecmasterPas = New-Object 'System.Windows.Forms.Form'
	$textboxSecPass = New-Object 'System.Windows.Forms.TextBox'
	$statusbarSecPass = New-Object 'System.Windows.Forms.StatusBar'
	$labelComputerName = New-Object 'System.Windows.Forms.Label'
	$textboxComputerName = New-Object 'System.Windows.Forms.TextBox'
	$buttonSearch = New-Object 'System.Windows.Forms.Button'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formCheckingSecmasterPas_Load={
		#TODO: Initialize Form Controls here
		$textboxComputerName.Text = $textboxComputerNameMainForm.Text
	}
	
	$buttonSearch_Click={
		#TODO: Place custom script here
		$computerName = $textboxComputerName.Text
		$statusbarSecPass.Text = "Searching..."
		try
		{
			$textboxSecPass.Text = "$(Get-ADComputer -Filter { name -like $computerName } -Properties ms-Mcs-AdmPwd).'ms-Mcs-AdmPwd'"
			$statusbarSecPass.Text = "Successfully done."
		}
		catch
		{
			$statusbarSecPass.Text = "Error : $($_.Exception.Message)"
		}
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formCheckingSecmasterPas.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
		$script:SecmasterPasswordForm_textboxSecPass = $textboxSecPass.Text
		$script:SecmasterPasswordForm_textboxComputerName = $textboxComputerName.Text
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonSearch.remove_Click($buttonSearch_Click)
			$formCheckingSecmasterPas.remove_Load($formCheckingSecmasterPas_Load)
			$formCheckingSecmasterPas.remove_Load($Form_StateCorrection_Load)
			$formCheckingSecmasterPas.remove_Closing($Form_StoreValues_Closing)
			$formCheckingSecmasterPas.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formCheckingSecmasterPas.SuspendLayout()
	#
	# formCheckingSecmasterPas
	#
	$formCheckingSecmasterPas.Controls.Add($textboxSecPass)
	$formCheckingSecmasterPas.Controls.Add($statusbarSecPass)
	$formCheckingSecmasterPas.Controls.Add($labelComputerName)
	$formCheckingSecmasterPas.Controls.Add($textboxComputerName)
	$formCheckingSecmasterPas.Controls.Add($buttonSearch)
	$formCheckingSecmasterPas.AutoScaleDimensions = '6, 13'
	$formCheckingSecmasterPas.AutoScaleMode = 'Font'
	$formCheckingSecmasterPas.ClientSize = '382, 133'
	$formCheckingSecmasterPas.Name = 'formCheckingSecmasterPas'
	$formCheckingSecmasterPas.Text = 'Checking Secmaster Password'
	$formCheckingSecmasterPas.add_Load($formCheckingSecmasterPas_Load)
	#
	# textboxSecPass
	#
	$textboxSecPass.Enabled = $False
	$textboxSecPass.Font = 'Microsoft Sans Serif, 18pt, style=Bold'
	$textboxSecPass.Location = '12, 58'
	$textboxSecPass.Name = 'textboxSecPass'
	$textboxSecPass.Size = '358, 35'
	$textboxSecPass.TabIndex = 4
	$textboxSecPass.TextAlign = 'Center'
	#
	# statusbarSecPass
	#
	$statusbarSecPass.Location = '0, 111'
	$statusbarSecPass.Name = 'statusbarSecPass'
	$statusbarSecPass.Size = '382, 22'
	$statusbarSecPass.TabIndex = 3
	$statusbarSecPass.Text = 'Ready ...'
	#
	# labelComputerName
	#
	$labelComputerName.AutoSize = $True
	$labelComputerName.Location = '12, 16'
	$labelComputerName.Name = 'labelComputerName'
	$labelComputerName.Size = '94, 17'
	$labelComputerName.TabIndex = 2
	$labelComputerName.Text = 'Computer name : '
	$labelComputerName.UseCompatibleTextRendering = $True
	#
	# textboxComputerName
	#
	$textboxComputerName.Location = '111, 13'
	$textboxComputerName.Name = 'textboxComputerName'
	$textboxComputerName.Size = '178, 20'
	$textboxComputerName.TabIndex = 1
	#
	# buttonSearch
	#
	$buttonSearch.Location = '295, 11'
	$buttonSearch.Name = 'buttonSearch'
	$buttonSearch.Size = '75, 23'
	$buttonSearch.TabIndex = 0
	$buttonSearch.Text = 'Search'
	$buttonSearch.UseCompatibleTextRendering = $True
	$buttonSearch.UseVisualStyleBackColor = $True
	$buttonSearch.add_Click($buttonSearch_Click)
	$formCheckingSecmasterPas.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formCheckingSecmasterPas.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formCheckingSecmasterPas.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formCheckingSecmasterPas.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$formCheckingSecmasterPas.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $formCheckingSecmasterPas.ShowDialog()

}
#endregion Source: SecmasterPasswordForm.psf

#Start the application
Main ($CommandLine)
